backend:
  name: git-gateway
  branch: main

locale: "es"

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "informacion"
    label: "Información Parroquial"
    files:
      - label: "Horarios de Misa"
        name: "misas"
        file: "content/info/misas.md"
        fields:
          - label: "Contenido y Horarios"
            name: "body"
            widget: "markdown"

      - label: "Confesiones"
        name: "confesiones"
        file: "content/info/confesiones.md"
        fields:
          - label: "Contenido y Horarios"
            name: "body"
            widget: "markdown"

      - label: "Secretaría Parroquial"
        name: "secretaria"
        file: "content/info/secretaria.md"
        fields:
          - label: "Información de Contacto y Horarios"
            name: "body"
            widget: "markdown"