backend:
  name: git-gateway
  branch: main

locale: "es"

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "informacion"
    label: "Información Parroquial"
    files:

      - label: "Horarios de Misa"
        name: "misas"
        file: "content/info/misas.md"
        fields:
          - label: "Horarios de misa"
            name: "horarios"
            widget: "list"
            fields:
              - { label: "Dia", name: "Dia", widget: "string" }
              - label: "Horarios"
                name: "Horarios"
                widget: "list"
                field: { label: "Hora", name: "hora", widget: "string" }

      - label: "Confesiones"
        name: "confesiones"
        file: "content/info/confesiones.md"
        fields:
          - label: "Horarios de confesiones"
            name: "horarios"
            widget: "list"
            fields:
              - { label: "Dia", name: "Dia", widget: "string" }
              - label: "Horarios"
                name: "Horarios"
                widget: "list"
                field: { label: "Hora", name: "hora", widget: "string" }

      - label: "Secretaría Parroquial"
        name: "secretaria"
        file: "content/info/secretaria.md"
        fields:

          - label: "Horarios de atención"
            name: "horarios"
            widget: "list"
            fields:
              - { label: "Dia", name: "Dia", widget: "string" }
              - { label: "Horarios", name: "Horarios", widget: "string" }

          - { label: "Telefono", name: "telefono", widget: "string" }

          - { label: "Numero de WhatsApp (solo numeros con codigo de pais)", name: "whatsapp", widget: "string" }
